name: Release Binary

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update system and install CA Certificates and fzf
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ca-certificates fzf

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.10"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --locked

      - name: Package binary
        run: uv run pyinstaller mangaplace/mangaplace.spec

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Archive the binary
        run: |
          cd dist
          zip mangaplace-${{ env.VERSION }}.zip mangaplace

      - name: Upload release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: dist/mangaplace-${{ env.VERSION }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
